name: CI Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 20 * * *" # Runs daily at 8pm UTC (9pm Spanish time)

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Netlify
        run: npx install netlify-cli@17.10.1 -g

      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          netlify deploy \
            --dir ./ \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }}